# Generated by Django 3.2.1 on 2021-05-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_questionsupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsUpdateUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specifications', models.FileField(upload_to='router_specifications')),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionsUpdate',
        ),
    ]
