# Generated by Django 3.2.1 on 2021-05-10 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_auto_20210510_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_group_title',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_group',
            field=models.CharField(default='', max_length=600),
        ),
    ]
